Modify nova-network title for Havana support
Signed-off-by: Emilien Macchi <emilien.macchi@enovance.com>

diff --git a/ocf/neutron-agent-dhcp b/ocf/neutron-agent-dhcp
--- a/ocf/neutron-agent-dhcp
+++ b/ocf/neutron-agent-dhcp
@@ -1,13 +1,12 @@
 #!/bin/sh
 #
 #
-# OpenStack Network Service (nova-network) (replaced by Neutron in Havana)
+# OpenStack DHCP Service (neutron-dhcp-agent)
 #
-# Description:  Manages an OpenStack Network Service (nova-network) process as an HA resource
+# Description:  Manages an OpenStack DHCP Service (neutron-dhcp-agent) process as an HA resource
 #
-# Authors: Sebastien Han & Emilien Macchi
-# Mainly inspired by the Nova Scheduler resource agent written by Sebastien Han : http://goo.gl/s8hOU
-# Which are also inspired by the resource agents written by Martin Gerhard Loschwitz from Hastexo: http://goo.gl/whLpr
+# Authors: Emilien Macchi
+# Mainly inspired by the Nova Network resource agent written by Emilien Macchi & Sebastien Han
 #
 # Support:      openstack@lists.launchpad.net
 # License:      Apache Software License (ASL) 2.0
@@ -18,11 +17,10 @@
 # OCF instance parameters:
 #   OCF_RESKEY_binary
 #   OCF_RESKEY_config
+#   OCF_RESKEY_plugin_config
 #   OCF_RESKEY_user
 #   OCF_RESKEY_pid
-#   OCF_RESKEY_database_server_port
 #   OCF_RESKEY_amqp_server_port
-#   OCF_RESKEY_zeromq
 #   OCF_RESKEY_additional_parameters
 #######################################################################
 # Initialization:
@@ -34,21 +32,19 @@
 
 # Fill in some defaults if no values are specified
 
-OCF_RESKEY_binary_default="nova-network"
-OCF_RESKEY_config_default="/etc/nova/nova.conf"
-OCF_RESKEY_user_default="nova"
+OCF_RESKEY_binary_default="neutron-dhcp-agent"
+OCF_RESKEY_config_default="/etc/neutron/neutron.conf"
+OCF_RESKEY_plugin_config_default="/etc/neutron/dhcp_agent.ini"
+OCF_RESKEY_user_default="neutron"
 OCF_RESKEY_pid_default="$HA_RSCTMP/$OCF_RESOURCE_INSTANCE.pid"
-OCF_RESKEY_database_server_port_default="3306"
 OCF_RESKEY_amqp_server_port_default="5672"
-OCF_RESKEY_zeromq_default="false"
 
 : ${OCF_RESKEY_binary=${OCF_RESKEY_binary_default}}
 : ${OCF_RESKEY_config=${OCF_RESKEY_config_default}}
+: ${OCF_RESKEY_plugin_config=${OCF_RESKEY_plugin_config_default}}
 : ${OCF_RESKEY_user=${OCF_RESKEY_user_default}}
 : ${OCF_RESKEY_pid=${OCF_RESKEY_pid_default}}
-: ${OCF_RESKEY_database_server_port=${OCF_RESKEY_database_server_port_default}}
 : ${OCF_RESKEY_amqp_server_port=${OCF_RESKEY_amqp_server_port_default}}
-: ${OCF_RESKEY_zeromq=${OCF_RESKEY_zeromq_default}}
 
 #######################################################################
 
@@ -56,7 +52,7 @@ usage() {
     cat <<UEND
         usage: $0 (start|stop|validate-all|meta-data|status|monitor)
 
-        $0 manages an OpenStack Network Service (nova-network) process as an HA resource 
+        $0 manages an OpenStack DHCP Service (neutron-dhcp-agent) process as an HA resource 
 
         The 'start' operation starts the networking service.
         The 'stop' operation stops the networking service.
@@ -72,55 +68,55 @@ meta_data() {
     cat <<END
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
-<resource-agent name="nova-network">
+<resource-agent name="neutron-dhcp-agent">
 <version>1.0</version>
 
 <longdesc lang="en">
-Resource agent for the OpenStack Nova Network Service (nova-network)
-May manage a nova-network instance or a clone set that 
-creates a distributed nova-network cluster.
+Resource agent for the OpenStack Neutron DHCP Service (neutron-dhcp-agent)
+May manage a neutron-dhcp-agent instance or a clone set that 
+creates a distributed neutron-dhcp-agent cluster.
 </longdesc>
-<shortdesc lang="en">Manages the OpenStack Network Service (nova-network)</shortdesc>
+<shortdesc lang="en">Manages the OpenStack DHCP Service (neutron-dhcp-agent)</shortdesc>
 <parameters>
 
 <parameter name="binary" unique="0" required="0">
 <longdesc lang="en">
-Location of the OpenStack Nova Network server binary (nova-network)
+Location of the OpenStack DHCP Server server binary (neutron-dhcp-agent)
 </longdesc>
-<shortdesc lang="en">OpenStack Nova Network server binary (nova-network)</shortdesc>
+<shortdesc lang="en">OpenStack DHCP Server server binary (neutron-dhcp-agent)</shortdesc>
 <content type="string" default="${OCF_RESKEY_binary_default}" />
 </parameter>
 
 <parameter name="config" unique="0" required="0">
 <longdesc lang="en">
-Location of the OpenStack Network Service (nova-network) configuration file
+Location of the OpenStack Neutron Service (neutron-server) configuration file
 </longdesc>
-<shortdesc lang="en">OpenStack Nova Network (nova-network) config file</shortdesc>
+<shortdesc lang="en">OpenStack DHCP Server (neutron-server) config file</shortdesc>
 <content type="string" default="${OCF_RESKEY_config_default}" />
+</parameter>
+
+<parameter name="plugin config" unique="0" required="0">
+<longdesc lang="en">
+Location of the OpenStack DHCP Service (neutron-dhcp-agent) configuration file
+</longdesc>
+<shortdesc lang="en">OpenStack DHCP Server (neutron-dhcp-agent) config file</shortdesc>
+<content type="string" default="${OCF_RESKEY_plugin_config_default}" />
 </parameter>
 
 <parameter name="user" unique="0" required="0">
 <longdesc lang="en">
-User running OpenStack Network Service (nova-network)
+User running OpenStack DHCP Service (neutron-dhcp-agent)
 </longdesc>
-<shortdesc lang="en">OpenStack Network Service (nova-network) user</shortdesc>
+<shortdesc lang="en">OpenStack DHCP Service (neutron-dhcp-agent) user</shortdesc>
 <content type="string" default="${OCF_RESKEY_user_default}" />
 </parameter>
 
 <parameter name="pid" unique="0" required="0">
 <longdesc lang="en">
-The pid file to use for this OpenStack Network Service (nova-network) instance
+The pid file to use for this OpenStack DHCP Service (neutron-dhcp-agent) instance
 </longdesc>
-<shortdesc lang="en">OpenStack Network Service (nova-network) pid file</shortdesc>
+<shortdesc lang="en">OpenStack DHCP Service (neutron-dhcp-agent) pid file</shortdesc>
 <content type="string" default="${OCF_RESKEY_pid_default}" />
-</parameter>
-
-<parameter name="database_server_port" unique="0" required="0">                                                                                                                                                              
-<longdesc lang="en">                                                                                                                                                                                                      
-The listening port number of the database server. Mandatory to perform a monitor check                                                                                                                                        
-</longdesc>                                                                                                                                                                                                               
-<shortdesc lang="en">Database listening port</shortdesc>                                                                                                                                                                      
-<content type="integer" default="${OCF_RESKEY_database_server_port_default}" />                                                                                                                                              
 </parameter>  
 
 <parameter name="amqp_server_port" unique="0" required="0">                                                                                                                                                              
@@ -131,19 +127,12 @@ The listening port number of the AMQP server. Mandatory to perform a monitor che
 <content type="integer" default="${OCF_RESKEY_amqp_server_port_default}" />                                                                                                                                              
 </parameter>      
 
-<parameter name="zeromq" unique="0" required="0">                                                                                                                                                              
-<longdesc lang="en">                                                                                                                                                                                                      
-If zeromq is used, this will disable the connection test to the AMQP server                                                                                                                                     
-</longdesc>                                                                                                                                                                                                               
-<shortdesc lang="en">Zero-MQ usage</shortdesc>                                                                                                                                                                      
-<content type="boolean" default="${OCF_RESKEY_zeromq_default}" />                                                                                                                                              
-</parameter>  
 
 <parameter name="additional_parameters" unique="0" required="0">
 <longdesc lang="en">
-Additional parameters to pass on to the OpenStack Network Service (nova-network)
+Additional parameters to pass on to the OpenStack DHCP Service (neutron-dhcp-agent)
 </longdesc>
-<shortdesc lang="en">Additional parameters for nova-network</shortdesc>
+<shortdesc lang="en">Additional parameters for neutron-dhcp-agent</shortdesc>
 <content type="string" />
 </parameter>
 
@@ -164,7 +153,7 @@ END
 #######################################################################
 # Functions invoked by resource manager actions
 
-nova_network_validate() {
+neutron_dhcp_agent_validate() {
     local rc
 
     check_binary $OCF_RESKEY_binary
@@ -190,12 +179,12 @@ nova_network_validate() {
     true
 }
 
-nova_network_status() {
+neutron_dhcp_agent_status() {
     local pid
     local rc
 
     if [ ! -f $OCF_RESKEY_pid ]; then
-        ocf_log info "OpenStack Nova Network (nova-network) is not running"
+        ocf_log info "OpenStack DHCP Server (neutron-dhcp-agent) is not running"
         return $OCF_NOT_RUNNING
     else
         pid=`cat $OCF_RESKEY_pid`
@@ -206,20 +195,17 @@ nova_network_status() {
     if [ $rc -eq 0 ]; then
         return $OCF_SUCCESS
     else
-        ocf_log info "Old PID file found, but OpenStack Nova Network (nova-network) is not running"
+        ocf_log info "Old PID file found, but OpenStack DHCP Server (neutron-dhcp-agent) is not running"
         return $OCF_NOT_RUNNING
     fi
 }
 
-nova_network_monitor() {
+neutron_dhcp_agent_monitor() {
     local rc
     local pid
-    local rc_db
-    local rc_amqp
-    local network_db_check
     local network_amqp_check
     
-    nova_network_status
+    neutron_dhcp_agent_status
     rc=$?
 
     # If status returned anything but success, return that immediately
@@ -228,72 +214,61 @@ nova_network_monitor() {
     fi
 
     # Check the connections according to the PID.
-    # We are sure to hit the scheduler process and not other nova process with the same connection behavior (for example nova-cert)
-	if ocf_is_true "$OCF_RESKEY_zeromq"; then
-	    pid=`cat $OCF_RESKEY_pid`
-	    network_db_check=`netstat -punt | grep -s "$OCF_RESKEY_database_server_port" | grep -s "$pid" | grep -qs "ESTABLISHED"`
-	    rc_db=$?
-	    if [ $rc_db -ne 0 ]; then
-	        ocf_log err "Nova Network is not connected to the database server: $rc_db"
-	        return $OCF_NOT_RUNNING
-	    fi
-	else
+    # We are sure to hit the scheduler process and not other Neutron process with the same connection behavior (for example neutron-server)
         pid=`cat $OCF_RESKEY_pid`
         # check the connections according to the PID
-        network_db_check=`netstat -punt | grep -s "$OCF_RESKEY_database_server_port" | grep -s "$pid" | grep -qs "ESTABLISHED"`
-        rc_db=$?
         network_amqp_check=`netstat -punt | grep -s "$OCF_RESKEY_amqp_server_port" | grep -s "$pid" | grep -qs "ESTABLISHED"`
-        rc_amqp=$?
-	    if [ $rc_amqp -ne 0 ] || [ $rc_db -ne 0 ]; then
-	        ocf_log err "Nova Network is not connected to the AMQP server and/or the database server: AMQP connection test returned $rc_amqp and database connection test returned $rc_db"
+        rc=$?
+	    if [ $rc -ne 0 ]; then
+	        ocf_log err "Neutron DHCP Server is not connected to the AMQP server : $rc"
 	        return $OCF_NOT_RUNNING
 	    fi
-	fi
 
-    ocf_log debug "OpenStack Nova Network (nova-network) monitor succeeded"
+    ocf_log debug "OpenStack DHCP Server (neutron-dhcp-agent) monitor succeeded"
     return $OCF_SUCCESS
 }
 
-nova_network_start() {
+neutron_dhcp_agent_start() {
     local rc
 
-    nova_network_status
+    neutron_dhcp_agent_status
     rc=$?
     if [ $rc -eq $OCF_SUCCESS ]; then
-        ocf_log info "OpenStack Nova Network (nova-network) already running"
+        ocf_log info "OpenStack DHCP Server (neutron-dhcp-agent) already running"
         return $OCF_SUCCESS
     fi
 
-    # run the actual nova-network daemon. Don't use ocf_run as we're sending the tool's output
+    # run the actual neutron-dhcp-agent daemon. Don't use ocf_run as we're sending the tool's output
     # straight to /dev/null anyway and using ocf_run would break stdout-redirection here.
     su ${OCF_RESKEY_user} -s /bin/sh -c "${OCF_RESKEY_binary} --config-file=$OCF_RESKEY_config \
-       $OCF_RESKEY_additional_parameters"' >> /dev/null 2>&1 & echo $!' > $OCF_RESKEY_pid
+       --config-file=$OCF_RESKEY_plugin_config --log-file=/var/log/neutron/dhcp-agent.log $OCF_RESKEY_additional_parameters"' >> \
+	/dev/null 2>&1 & echo $!' > $OCF_RESKEY_pid
 
     # Spin waiting for the server to come up.
     # Let the CRM/LRM time us out if required
     while true; do
-    nova_network_monitor
+    neutron_dhcp_agent_monitor
     rc=$?
     [ $rc -eq $OCF_SUCCESS ] && break
     if [ $rc -ne $OCF_NOT_RUNNING ]; then
-        ocf_log err "OpenStack Nova Network (nova-network) start failed"
+        ocf_log err "OpenStack DHCP Server (neutron-dhcp-agent) start failed"
         exit $OCF_ERR_GENERIC
     fi
     sleep 1
     done
 
-    ocf_log info "OpenStack Nova Network (nova-network) started"
+    ocf_log info "OpenStack DHCP Server (neutron-dhcp-agent) started"
     return $OCF_SUCCESS
 }
 
-nova_network_stop() {
+neutron_dhcp_agent_stop() {
     local rc
     local pid
 
-    nova_network_status
+    neutron_dhcp_agent_status
     rc=$?
     if [ $rc -eq $OCF_NOT_RUNNING ]; then
-        ocf_log info "OpenStack Nova Network (nova-network) already stopped"
+        ocf_log info "OpenStack DHCP Server (neutron-dhcp-agent) already stopped"
         return $OCF_SUCCESS
     fi
 
@@ -303,7 +278,7 @@ nova_network_stop() {
     ocf_run kill -s TERM $pid
     rc=$?
     if [ $rc -ne 0 ]; then
-        ocf_log err "OpenStack Nova Network (nova-network) couldn't be stopped"
+        ocf_log err "OpenStack DHCP Server (neutron-dhcp-agent) couldn't be stopped"
         exit $OCF_ERR_GENERIC
     fi
 
@@ -314,26 +289,26 @@ nova_network_stop() {
     fi
     count=0
     while [ $count -lt $shutdown_timeout ]; do
-        nova_network_status
+        neutron_dhcp_agent_status
         rc=$?
         if [ $rc -eq $OCF_NOT_RUNNING ]; then
             break
         fi
         count=`expr $count + 1`
         sleep 1
-        ocf_log debug "OpenStack Nova Network (nova-network) still hasn't stopped yet. Waiting ..."
+        ocf_log debug "OpenStack DHCP Server (neutron-dhcp-agent) still hasn't stopped yet. Waiting ..."
     done
 
-    nova_network_status
+    neutron_dhcp_agent_status
     rc=$?
     if [ $rc -ne $OCF_NOT_RUNNING ]; then
         # SIGTERM didn't help either, try SIGKILL
-        ocf_log info "OpenStack Nova Network (nova-network) failed to stop after ${shutdown_timeout}s \
+        ocf_log info "OpenStack DHCP Server (neutron-dhcp-agent) failed to stop after ${shutdown_timeout}s \
           using SIGTERM. Trying SIGKILL ..."
         ocf_run kill -s KILL $pid
     fi
 
-    ocf_log info "OpenStack Nova Network (nova-network) stopped"
+    ocf_log info "OpenStack DHCP Server (neutron-dhcp-agent) stopped"
 
     rm -f $OCF_RESKEY_pid
 
@@ -350,14 +325,14 @@ case "$1" in
 esac
 
 # Anything except meta-data and help must pass validation
-nova_network_validate || exit $?
+neutron_dhcp_agent_validate || exit $?
 
 # What kind of method was invoked?
 case "$1" in
-  start)        nova_network_start;;
-  stop)         nova_network_stop;;
-  status)       nova_network_status;;
-  monitor)      nova_network_monitor;;
+  start)        neutron_dhcp_agent_start;;
+  stop)         neutron_dhcp_agent_stop;;
+  status)       neutron_dhcp_agent_status;;
+  monitor)      neutron_dhcp_agent_monitor;;
   validate-all) ;;
   *)            usage
                 exit $OCF_ERR_UNIMPLEMENTED;;
