Update nova-api monitor function
Now the monitor function requests the API service.

diff --git a/ocf/nova-api b/ocf/nova-api
--- a/ocf/nova-api
+++ b/ocf/nova-api
@@ -36,15 +36,15 @@ OCF_RESKEY_binary_default="nova-api"
 OCF_RESKEY_config_default="/etc/nova/nova.conf"
 OCF_RESKEY_user_default="nova"
 OCF_RESKEY_pid_default="$HA_RSCTMP/$OCF_RESOURCE_INSTANCE.pid"
-OCF_RESKEY_monitor_binary_default="netstat"
-OCF_RESKEY_api_listened_port_default="8773|8774|8775|8776"
+OCF_RESKEY_url_default="http://127.0.0.1:8774/v1.1/"
+OCF_RESKEY_keystone_url_default="http://127.0.0.1:5000/v2.0/tokens"
 
 : ${OCF_RESKEY_binary=${OCF_RESKEY_binary_default}}
 : ${OCF_RESKEY_config=${OCF_RESKEY_config_default}}
 : ${OCF_RESKEY_user=${OCF_RESKEY_user_default}}
 : ${OCF_RESKEY_pid=${OCF_RESKEY_pid_default}}
-: ${OCF_RESKEY_monitor_binary=${OCF_RESKEY_monitor_binary_default}}
-: ${OCF_RESKEY_api_listened_port=${OCF_RESKEY_api_listened_port_default}}
+: ${OCF_RESKEY_url=${OCF_RESKEY_url_default}}
+: ${OCF_RESKEY_keystone_url=${OCF_RESKEY_keystone_url_default}}
 
 #######################################################################
 
@@ -111,9 +111,50 @@ The pid file to use for this OpenStack Nova API (nova-api) instance
 <content type="string" default="${OCF_RESKEY_pid_default}" />
 </parameter>
 
+<parameter name="url" unique="0" required="0">
+<longdesc lang="en">
+The default URL to use for monitoring this instance (nova-api) via curl. Important note: the monitor function doesn't accept http return code different than 200, for instance redirection code will generate an error. Don't forget the '/' at the end of your url endpoint. For example http://127.0.0.1:8774/v1.1 won't work and http://127.0.0.1:8774/v1.1/ will.
+</longdesc>
+<shortdesc lang="en">OpenStack Nova API (nova-api) monitor url</shortdesc>
+<content type="string" default="${OCF_RESKEY_url_default}" />
+</parameter>
+
+<parameter name="keystone_url" unique="0" required="0">
+<longdesc lang="en">
+The default URL to use to acquire a Nova API (nova-api) token for monitoring this instance
+of OpenStack Nova API (nova-api)
+</longdesc>
+<shortdesc lang="en">OpenStack Nova API (nova-api) url</shortdesc>
+<content type="string" default="${OCF_RESKEY_keystone_url_default}" />
+</parameter>
+
+<parameter name="os_username" unique="0" required="0">
+<longdesc lang="en">
+The username to use when connecting with Nova API (nova-api) for monitoring purposes
+</longdesc>
+<shortdesc lang="en">Nova API (nova-api) monitoring login</shortdesc>
+<content type="string" />
+</parameter>
+
+<parameter name="os_password" unique="0" required="0">
+<longdesc lang="en">
+The password to use when connecting Nova API (nova-api) for monitoring purposes
+</longdesc>
+<shortdesc lang="en">Nova API (nova-api) monitoring password</shortdesc>
+<content type="string" />
+</parameter>
+
+<parameter name="os_tenant_name" unique="0" required="0">
+<longdesc lang="en">
+The tenant to use when connecting Nova API (nova-api) for monitoring purposes
+</longdesc>
+<shortdesc lang="en">Nova API (nova-api) monitoring tenant</shortdesc>
+<content type="string" />
+</parameter>
+
 <parameter name="additional_parameters" unique="0" required="0">
 <longdesc lang="en">
-Additional parameters to pass on to the OpenStack Nova API (nova-api)
+Additional parameters to pass on to the OpenStack NovaAPI (nova-api)
 </longdesc>
 <shortdesc lang="en">Additional parameters for nova-api</shortdesc>
 <content type="string" />
@@ -194,18 +235,19 @@ nova_api_monitor() {
         return $rc
     fi
 
-    # Check whether we are supposed to monitor by logging into nova-api
-    # and do it if that's the case.
-    if ! check_binary $OCF_RESKEY_monitor_binary; then 
-        ocf_log warn "$OCF_RESKEY_monitor_binary missing, can not monitor!" 
-    else
-        # Check ec2, osapi_compute, osapi_volume and metadata ports
-        API_LIST_CHECK=`"$OCF_RESKEY_monitor_binary" -a | grep -sE "\"$OCF_RESKEY_api_listened_port\"" | grep -sq "LISTEN"`
-    fi
-    rc=$?
-    if [ $rc -ne 0 ]; then
-        ocf_log err "Nova API doesn't listen properly: $rc"
-        return $OCF_NOT_RUNNING
+    # Check detailed information about this specific version of the API.
+    if [ -n "$OCF_RESKEY_os_username" ] && [ -n "$OCF_RESKEY_os_password" ] \
+    && [ -n "$OCF_RESKEY_os_tenant_name" ] && [ -n "$OCF_RESKEY_keystone_url" ]; then
+        TOKEN=`curl -s -d  "{\"auth\":{\"passwordCredentials\": {\"username\": \"$OCF_RESKEY_os_username\", \
+          \"password\": \"$OCF_RESKEY_os_password\"}, \"tenantName\": \"$OCF_RESKEY_os_tenant_name\"}}" \
+          -H "Content-type: application/json" $OCF_RESKEY_keystone_url | tr ',' '\n' | grep '"id":' \
+          | cut -d'"' -f4 | head --lines 1` 
+        HTTP_CODE=`curl --write-out %{http_code} --output /dev/null -sH "X-Auth-Token: $TOKEN" $OCF_RESKEY_url`
+        rc=$?
+        if [ $rc -ne 0 ] || [ $CODE -ne 200 ]; then
+            ocf_log err "Failed to connect to the OpenStack Nova API (nova-api): $rc and $HTTP_CODE"
+            return $OCF_NOT_RUNNING
+        fi
     fi
 
     ocf_log debug "OpenStack Nova API (nova-api) monitor succeeded"
